"use strict";(self.webpackChunksailpoint_developer_portal=self.webpackChunksailpoint_developer_portal||[]).push([[54800],{83389:(e,n,t)=>{t.r(n),t.d(n,{assets:()=>y,contentTitle:()=>g,default:()=>k,frontMatter:()=>m,metadata:()=>f,toc:()=>v});var o=t(3905),r=Object.defineProperty,i=Object.defineProperties,a=Object.getOwnPropertyDescriptors,s=Object.getOwnPropertySymbols,c=Object.prototype.hasOwnProperty,l=Object.prototype.propertyIsEnumerable,d=(e,n,t)=>n in e?r(e,n,{enumerable:!0,configurable:!0,writable:!0,value:t}):e[n]=t,p=(e,n)=>{for(var t in n||(n={}))c.call(n,t)&&d(e,t,n[t]);if(s)for(var t of s(n))l.call(n,t)&&d(e,t,n[t]);return e},u=(e,n)=>i(e,a(n)),h=(e,n)=>{var t={};for(var o in e)c.call(e,o)&&n.indexOf(o)<0&&(t[o]=e[o]);if(null!=e&&s)for(var o of s(e))n.indexOf(o)<0&&l.call(e,o)&&(t[o]=e[o]);return t};const m={id:"error-handling",title:"Error Handling",pagination_label:"Error Handling",sidebar_label:"Error Handling",sidebar_position:3,sidebar_class_name:"errorHandling",keywords:["connectivity","connectors","error handling"],description:"If the code fails due to validation issues, connectivity, or configuration errors, you can handle the error and provide the user with information about what went wrong.",slug:"/connectivity/saas-connectivity/in-depth/error-handling",tags:["Connectivity"]},g=void 0,f={unversionedId:"connectivity/saas-connectivity/in-depth/error-handling",id:"connectivity/saas-connectivity/in-depth/error-handling",title:"Error Handling",description:"If the code fails due to validation issues, connectivity, or configuration errors, you can handle the error and provide the user with information about what went wrong.",source:"@site/docs/connectivity/saas-connectivity/in-depth/error-handling.md",sourceDirName:"connectivity/saas-connectivity/in-depth",slug:"/connectivity/saas-connectivity/in-depth/error-handling",permalink:"/docs/connectivity/saas-connectivity/in-depth/error-handling",draft:!1,editUrl:"https://github.com/sailpoint-oss/developer-community-site/edit/main/docs/connectivity/saas-connectivity/in-depth/error-handling.md",tags:[{label:"Connectivity",permalink:"/docs/tags/connectivity"}],version:"current",lastUpdatedBy:"GitHub Action Bot",lastUpdatedAt:1720812556,formattedLastUpdatedAt:"Jul 12, 2024",sidebarPosition:3,frontMatter:{id:"error-handling",title:"Error Handling",pagination_label:"Error Handling",sidebar_label:"Error Handling",sidebar_position:3,sidebar_class_name:"errorHandling",keywords:["connectivity","connectors","error handling"],description:"If the code fails due to validation issues, connectivity, or configuration errors, you can handle the error and provide the user with information about what went wrong.",slug:"/connectivity/saas-connectivity/in-depth/error-handling",tags:["Connectivity"]},sidebar:"openApiSidebar",previous:{title:"Debugging",permalink:"/docs/connectivity/saas-connectivity/in-depth/debugging"},next:{title:"Linting",permalink:"/docs/connectivity/saas-connectivity/in-depth/linting"}},y={},v=[{value:"Connector Errors",id:"connector-errors",level:2},{value:"Not Found Error Type",id:"not-found-error-type",level:2},{value:"Custom Errors",id:"custom-errors",level:2},{value:"Recommended custom exceptions and examples of when to use them",id:"recommended-custom-exceptions-and-examples-of-when-to-use-them",level:2},{value:"InvalidConfigurationException",id:"invalidconfigurationexception",level:4},{value:"InsufficientPermissionException",id:"insufficientpermissionexception",level:4},{value:"InvalidRequestException",id:"invalidrequestexception",level:4},{value:"ObjectAlreadyExistsException",id:"objectalreadyexistsexception",level:4},{value:"InvalidResponseException",id:"invalidresponseexception",level:4},{value:"TimeoutException",id:"timeoutexception",level:4}],b={toc:v},x="wrapper";function k(e){var n=e,{components:t}=n,r=h(n,["components"]);return(0,o.kt)(x,u(p(p({},b),r),{components:t,mdxType:"MDXLayout"}),(0,o.kt)("p",null,"If the code fails due to validation issues, connectivity or configuration errors, you can handle the error and provide the user with information about what went wrong. Properly handled errors make it easier to debug and identify what happened in your connector when something goes wrong."),(0,o.kt)("h2",p({},{id:"connector-errors"}),"Connector Errors"),(0,o.kt)("p",null,"The connector SDK has a built-in ConnectorError to use in your project to handle most generic errors:"),(0,o.kt)("p",null,(0,o.kt)("a",p({parentName:"p"},{href:"https://github.com/sailpoint-oss/airtable-example-connector/blob/main/src/airtable.ts"}),"airtable.ts")),(0,o.kt)("pre",null,(0,o.kt)("code",p({parentName:"pre"},{className:"language-javascript"}),"import { ConnectorError } from \"@sailpoint/connector-sdk\"\n\n...\n\nexport class AirtableClient {\n\n...\n\n    async getAllAccounts(): Promise<AirtableAccount[]> {\n        return this.airTableBase('Users').select({\n            view: 'Grid view'\n        }).firstPage().then(records => {\n            const recordArray: Array<AirtableAccount> = []\n            for (const record of records) {\n                recordArray.push(AirtableAccount.createWithRecords(record))\n            }\n            return recordArray\n        }).catch(err => {\n            throw new ConnectorError('error while getting accounts: ' + err)\n        })\n    }\n")),(0,o.kt)("h2",p({},{id:"not-found-error-type"}),"Not Found Error Type"),(0,o.kt)("p",null,'The connector SDK offers a special error type of "Not Found". This error signals to ISC that the specific account is not in the source system. If the account should be in the source system, ISC will then call the connector ',(0,o.kt)("inlineCode",{parentName:"p"},"std:account:create")," command to create the account."),(0,o.kt)("p",null,"Here is an example:"),(0,o.kt)("pre",null,(0,o.kt)("code",p({parentName:"pre"},{className:"language-javascript"}),'.stdAccountUpdate(async (context: Context, input: StdAccountUpdateInput, res: Response<StdAccountUpdateOutput>) => {\n    const account = await myClient.getAccount(input.identity)\n    if (!account) {\n        // account was not found, but identity now has the account and expects it to be there!\n        // Send an error message to Identity Security Cloud so the account is automatically created\n        if (!account) {\n            throw new ConnectorError("account is not found", ConnectorErrorType.NotFound)\n        }\n    }\n\n    ... perform normal account update logic below\n\n')),(0,o.kt)("h2",p({},{id:"custom-errors"}),"Custom Errors"),(0,o.kt)("p",null,"You can also create custom errors and use them in your code to give more meaningful and specific responses to error states. For example, when you are configuring your connector, it is recommended that you throw an ",(0,o.kt)("inlineCode",{parentName:"p"},"InvalidConfigurationError")," instead of a generic ConnectorError. To do this, create the custom error:"),(0,o.kt)("p",null,(0,o.kt)("a",p({parentName:"p"},{href:"https://github.com/sailpoint-oss/airtable-example-connector/blob/main/src/errors/invalid-configuration-error.ts"}),"invalid-configuration-error.ts")),(0,o.kt)("pre",null,(0,o.kt)("code",p({parentName:"pre"},{className:"language-javascript"}),"import {ConnectorError, ConnectorErrorType} from '@sailpoint/connector-sdk';\n\n/**\n * Thrown when an application missing configuration during initialization\n */\n\nexport class InvalidConfigurationException extends ConnectorError {\n  /**\n   * Constructor\n   * @param message Error message\n   * @param type ConnectorErrorType they type of error\n   */\n  constructor(message: string, type?: ConnectorErrorType) {\n    super(message, type);\n    this.name = 'InvalidConfigurationException';\n  }\n}\n")),(0,o.kt)("p",null,"Then throw the error in your code:"),(0,o.kt)("p",null,(0,o.kt)("a",p({parentName:"p"},{href:"https://github.com/sailpoint-oss/airtable-example-connector/blob/main/src/airtable.ts"}),"airtable.ts")),(0,o.kt)("pre",null,(0,o.kt)("code",p({parentName:"pre"},{className:"language-javascript"}),"import { InvalidConfigurationException } from \"./errors/invalid-configuration-error\"\n\nexport class AirtableClient {\n    private readonly airTableBase: Airtable.Base\n    constructor(config: any) {\n        // Fetch necessary properties from config.\n        // Following properties actually do not exist in the config -- it just serves as an example.\n        if (config.apiKey == null) {\n            throw new InvalidConfigurationException('token must be provided from config')\n        }\n        if (config.airtableBase == null) {\n            throw new InvalidConfigurationException('airtableBase base id needed')\n        }\n        Airtable.configure({apiKey: config.apiKey})\n        this.airTableBase = Airtable.base(config.airtableBase)\n    }\n\n    ...\n\n}\n")),(0,o.kt)("h2",p({},{id:"recommended-custom-exceptions-and-examples-of-when-to-use-them"}),"Recommended custom exceptions and examples of when to use them"),(0,o.kt)("h4",p({},{id:"invalidconfigurationexception"}),"InvalidConfigurationException"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},"Use this exception during any operation if the connector requires a certain configuration to connect to the managed-system, but the configuration is either faulty or not provided. This could happen before sending a request to the managed system.")),(0,o.kt)("h4",p({},{id:"insufficientpermissionexception"}),"InsufficientPermissionException"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},"Use this exception during any operation if the connector gets a known managed system exception indicating a lack of permission.")),(0,o.kt)("h4",p({},{id:"invalidrequestexception"}),"InvalidRequestException"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},"Use this exception during any operation if the connector is creating messages to be sent to the managed system but is failing to create a message. This could happen before sending a request to the managed system.")),(0,o.kt)("h4",p({},{id:"objectalreadyexistsexception"}),"ObjectAlreadyExistsException"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},"Use this exception during the provisioning operation of the type create(only) if the connector is trying to create an entity that already exists on the managed system.")),(0,o.kt)("h4",p({},{id:"invalidresponseexception"}),"InvalidResponseException"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},"Use this exception during aggregation or in the getObject when the connector is unable to parse data received from managed system. This could happen if something fails when converting a managed system response to a ResourceObject.")),(0,o.kt)("h4",p({},{id:"timeoutexception"}),"TimeoutException"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},"This is intended for cases in which the connector receives timeout related error/exceptions from the managed system.")))}k.isMDXComponent=!0}}]);